### ISSUE TITLE
Enable travis-ci for resilience-for-software

### ISSUE THREAD

**Issue by snakescott** [res-eng/resilience-for-software#1]
Follow steps 1-3 @ https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci, which require repo owner permissions. This will allow integration with precommit markdown linting including doctoc, as can be seen in https://github.com/snakescott/awesome-dumpsterfire

FYI @asottile

**Comment by snakescott** [comment]
I can help if you need it :-D

**Comment by lorin** [comment]
I think this is set up now. I pushed a `.travis.yml` file and it [triggered a Travis CI build](https://travis-ci.org/res-eng/resilience-for-software/builds/548518553#L1).

(The build failed, but it least the Travis machinery seems to be wired up properly).
